spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mtld?serverTimezone=UTC&characterEncoding=UTF-8
    username: mtld
    password: mtld106@#
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true;
        use_sql_comments: true
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 500MB
  security:
    oauth2:
      client:
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            userInfo-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
        registration:
          kakao:
            client-id: b16fa4858c60ea9d4f042ea3b51165db
            client-secret: evXGUWIVYQfidcszzUZOTiDovjQxGBeD
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:3000/login/oauth2/kakao
            scope:
              - profile_nickname
              - account_email
              - gender
              - age_range
            client-name: Kakao
  redis:
    host: localhost
    port: 6379


logging.level:
  org.hibernate.SQL: debug
  org.apache.http: DEBUG
  httpclient.wire: debug


server.error.include-message: always
jwt:
  secret: clsdfSDFKSJ3oLXSDFKJEsdkfjsekfESDfksef3eZS10ZWNoLXNwcmsf3Dkdfsdfssa3sdfMNCdvbncrt5sdfq3sdfsf

cloud:
  aws:
    credentials:
      accessKey: AKIAZNX4V6HMO2OO6ZF5
      secretKey: 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
    stack:
      auto: false
    s3.bucket: a106mtld
#    s3.bucket.url:
    region:
      static: ap-northeast-2
